#!/usr/bin/env python3
#
# Kustomize plugin for generating secrets from Secret Manager:
#   https://cloud.google.com/secret-manager
#
# Requires GCP Cloud SDK version 281.0 or higher
#

import shlex
import subprocess
import sys
import yaml

config_file = open(sys.argv[1], 'r')
config_yaml = yaml.load(config_file, Loader=yaml.SafeLoader)

if config_yaml['config']['type'] in  ['generic', 'tls', 'docker-registry']:
  secret_type = config_yaml['config']['type']
else:
  secret_type = 'generic'

if secret_type == 'generic':
  base = """apiVersion: v1
kind: Secret
type: Opaque
"""
  output = yaml.load(base, Loader=yaml.SafeLoader)
  output['namespace'] = config_yaml['namespace']
  output['metadata'] = {'name': config_yaml['metadata']['name']}

output['data'] = {}
for source_name, target_name in config_yaml['literal-mappings'].items():
  get_secret_cmd = 'gcloud secrets versions access latest --secret="{}" --project {} --format yaml'.format(source_name, config_yaml['config']['project'])
  cmd_output = subprocess.check_output(shlex.split(get_secret_cmd))
  secret_content = yaml.load(cmd_output, Loader=yaml.SafeLoader)['payload']['data']
  output['data'].update({target_name: secret_content})

output_yaml = yaml.dump(output)
print(output_yaml)
